### ISSUE TITLE
Tables doesn't show up

### ISSUE THREAD

**Issue by viniciusfs** [mikejpeters/hgweb-boundstate-theme#8]
Tables in summary, shortlog and other pages does not show up.

Here is an screenshot example:

![Image of Yaktocat](http://tmp.ultrav.com.br/vinicius/boundstate-theme.png)

I notice this error on Apache logs:

```
Traceback (most recent call last):, referer: http://src.ultrav.com.br/
  File "/var/www/src.ultrav.com.br/hgwebdir.cgi", line 11, in <module>, referer: http://src.ultrav.com.br/
    wsgicgi.launch(application), referer: http://src.ultrav.com.br/
  File "/usr/lib64/python2.6/site-packages/mercurial/hgweb/wsgicgi.py", line 69, in launch, referer: http://src.ultrav.com.br/
    for chunk in content:, referer: http://src.ultrav.com.br/
  File "/usr/lib64/python2.6/site-packages/mercurial/util.py", line 220, in increasingchunks, referer: http://src.ultrav.com.br/
    for chunk in source:, referer: http://src.ultrav.com.br/
  File "/usr/lib64/python2.6/site-packages/mercurial/templater.py", line 60, in process, referer: http://src.ultrav.com.br/
    item = iters[0].next(), referer: http://src.ultrav.com.br/
  File "/usr/lib64/python2.6/site-packages/mercurial/templater.py", line 60, in process, referer: http://src.ultrav.com.br/
    item = iters[0].next(), referer: http://src.ultrav.com.br/
  File "/usr/lib64/python2.6/site-packages/mercurial/templater.py", line 60, in process, referer: http://src.ultrav.com.br/
    item = iters[0].next(), referer: http://src.ultrav.com.br/
  File "/usr/lib64/python2.6/site-packages/mercurial/templater.py", line 77, in _format, referer: http://src.ultrav.com.br/
    raise SyntaxError(_("error expanding '%s%%%s'") % (key, format)), referer: http://src.ultrav.com.br/
SyntaxError: error expanding 'name%urlparameter', referer: http://src.ultrav.com.br/
```

**Comment by MilesParker** [comment]
I have exactly the same issue.. :( To bad because it's a really huge improvement over built-ion mercurial themes.

**Comment by mikejpeters** [comment]
@MilesParker or @viniciusfs: can you please let me know if this is fixed by the latest commit? For some reason I couldn't reproduce this error but I removed reference to `name%urlparameter` so hopefully it's fixed.

**Comment by MilesParker** [comment]
Yep, that works, thanks! I'm seeing some other issues, but I'll file separately. Thanks for quick response!
